name: 'deploy-marketing'

on:
  push:
    branches:
      - main
    paths:
      - 'frameworks-mc-example/packages/marketing/**'

defaults:
  run:
    working-directory: 'frameworks-mc-example/packages/marketing'

jobs:
  build_marketing:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3

        - name: 'Installing dependencies'
          run: npm install
        - name: 'Builds application'
          run: npm run build

        - uses: shinyinc/action-aws-cli@v1.2
        - name: 'Syncs s3 bucket with marketing latest'
          run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/marketing/latest
          env: 
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: 'us-east-1'

    


