name: 'deploy-marketing'

on:
  push:
    branches:
      - main
    paths:
      - 'frameworks-mc-example/packages/marketing/**'

defaults:
  run:
    working-directory: 'frameworks-mc-example/packages/marketing'

jobs:
  build_marketing:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3

        - name: 'Installing dependencies'
          run: npm install
        - run: npm run build
    
